### ISSUE TITLE
could not open AIF-C file

### ISSUE THREAD

**Issue by fmdallas** [hughrawlinson/SNDCNV#1]
> > > f = aifc.open('hello.aiff','r')
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "aifc.py", line 928, in open
> > >     return Aifc_read(f)
> > >   File "aifc.py", line 340, in **init**
> > >     self.initfp(f)
> > >   File "aifc.py", line 306, in initfp
> > >     self._read_comm_chunk(chunk)
> > >   File "aifc.py", line 490, in _read_comm_chunk
> > >     raise Error, 'cannot read compressed AIFF-C files'
> > > aifc.Error: cannot read compressed AIFF-C files

**Comment by fmdallas** [comment]
it seems that the afire module doesn't function properly.

**Comment by hughrawlinson** [comment]
@fmdallas this is a super old unmaintained repo, I would suggest you not use it, and use the [python aifc module](https://docs.python.org/2/library/aifc.html) to handle your compressed aiff needs.
